### ISSUE TITLE
Question about the BCP based model

### ISSUE THREAD

**Issue by jinggqu** [chy-upc/ABD#6]
Thank you for the valuable work you have done.

However, I have encountered a problem while looking at the code ([train_ACDC_BCP.py](https://github.com/chy-upc/ABD/blob/main/code/train_ACDC_BCP.py)) where the section related to the module “ABD-R” is missing in that file.

Therefore, could you please point out the corresponding section of ABD-R in that file? Or the method does not use that module (ABD-R)?

I hope to receive your reply, thank you!

**Comment by chy-upc** [comment]
Thank you for your question.
I apologize for the mistake due to my oversight; the function name was written incorrectly, and it has now been corrected. (Modify file: train_ACDC_BCP.py, train_ACDC_Cross_Teaching.py, train_PROMISE12.py, displacement.py)
Since the BCP model inputs to the student model are labeled and unlabeled images after copy-paste, we can only treat them as unlabeled images for ABD-R operations, and no longer perform ABD-I operations.

**Comment by jinggqu** [comment]
Thanks for the reply and the code fix, now it makes sense.
